# Generated by Django 4.0.4 on 2022-05-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('avgPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
